/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CloudtrainChatbot {
        "apiKey": string;
        "avatarUrl"?: string;
        /**
          * @default 'https://cloudtrain.ai'
         */
        "baseUrl": string;
        "botName"?: string;
        /**
          * @default []
         */
        "chatSuggestions": string[];
        /**
          * If true, the chat panel opens automatically when the chatbot mounts. Useful for demos, onboarding flows, or pages where engagement is desired.
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * @default false
         */
        "hideBranding": boolean;
        /**
          * @default {}
         */
        "meta": Object;
        /**
          * @default 'bottom-right'
         */
        "position": 'bottom-right' | 'bottom-left';
        /**
          * Milliseconds between each character reveal in the streaming animation. `0` (default) shows characters as fast as they arrive from the network. A positive value (e.g. `20`) produces a typewriter effect.
          * @default 0
         */
        "revealDelayMs": number;
        /**
          * @default 'system'
         */
        "theme": 'light' | 'dark' | 'system';
        /**
          * @default 'How can I help you today?'
         */
        "welcomeMessage": string;
        "welcomeSubtitle"?: string;
    }
}
export interface CloudtrainChatbotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCloudtrainChatbotElement;
}
declare global {
    interface HTMLCloudtrainChatbotElementEventMap {
        "chatOpened": void;
        "chatClosed": void;
        "messageSent": { text: string };
        "messageReceived": { text: string };
        "conversationReset": void;
        "errorOccurred": { message: string };
    }
    interface HTMLCloudtrainChatbotElement extends Components.CloudtrainChatbot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCloudtrainChatbotElementEventMap>(type: K, listener: (this: HTMLCloudtrainChatbotElement, ev: CloudtrainChatbotCustomEvent<HTMLCloudtrainChatbotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCloudtrainChatbotElementEventMap>(type: K, listener: (this: HTMLCloudtrainChatbotElement, ev: CloudtrainChatbotCustomEvent<HTMLCloudtrainChatbotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCloudtrainChatbotElement: {
        prototype: HTMLCloudtrainChatbotElement;
        new (): HTMLCloudtrainChatbotElement;
    };
    interface HTMLElementTagNameMap {
        "cloudtrain-chatbot": HTMLCloudtrainChatbotElement;
    }
}
declare namespace LocalJSX {
    interface CloudtrainChatbot {
        "apiKey": string;
        "avatarUrl"?: string;
        /**
          * @default 'https://cloudtrain.ai'
         */
        "baseUrl"?: string;
        "botName"?: string;
        /**
          * @default []
         */
        "chatSuggestions"?: string[];
        /**
          * If true, the chat panel opens automatically when the chatbot mounts. Useful for demos, onboarding flows, or pages where engagement is desired.
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * @default false
         */
        "hideBranding"?: boolean;
        /**
          * @default {}
         */
        "meta"?: Object;
        /**
          * Fired when the chat panel closes.
         */
        "onChatClosed"?: (event: CloudtrainChatbotCustomEvent<void>) => void;
        /**
          * Fired when the chat panel opens.
         */
        "onChatOpened"?: (event: CloudtrainChatbotCustomEvent<void>) => void;
        /**
          * Fired when the user resets the conversation.
         */
        "onConversationReset"?: (event: CloudtrainChatbotCustomEvent<void>) => void;
        /**
          * Fired when an error happens during send/stream. Detail: error message.
         */
        "onErrorOccurred"?: (event: CloudtrainChatbotCustomEvent<{ message: string }>) => void;
        /**
          * Fired when a complete AI reply has finished streaming. Detail: the final text.
         */
        "onMessageReceived"?: (event: CloudtrainChatbotCustomEvent<{ text: string }>) => void;
        /**
          * Fired when the user submits a message. Detail: the message text.
         */
        "onMessageSent"?: (event: CloudtrainChatbotCustomEvent<{ text: string }>) => void;
        /**
          * @default 'bottom-right'
         */
        "position"?: 'bottom-right' | 'bottom-left';
        /**
          * Milliseconds between each character reveal in the streaming animation. `0` (default) shows characters as fast as they arrive from the network. A positive value (e.g. `20`) produces a typewriter effect.
          * @default 0
         */
        "revealDelayMs"?: number;
        /**
          * @default 'system'
         */
        "theme"?: 'light' | 'dark' | 'system';
        /**
          * @default 'How can I help you today?'
         */
        "welcomeMessage"?: string;
        "welcomeSubtitle"?: string;
    }
    interface IntrinsicElements {
        "cloudtrain-chatbot": CloudtrainChatbot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cloudtrain-chatbot": LocalJSX.CloudtrainChatbot & JSXBase.HTMLAttributes<HTMLCloudtrainChatbotElement>;
        }
    }
}
