/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CapturedLead, PreChatField } from "./components/cloudtrain-chatbot/cloudtrain-chatbot";
export { CapturedLead, PreChatField } from "./components/cloudtrain-chatbot/cloudtrain-chatbot";
export namespace Components {
    interface CloudtrainChatbot {
        "apiKey": string;
        "avatarUrl"?: string;
        /**
          * @default 'https://cloudtrain.ai'
         */
        "baseUrl": string;
        "botName"?: string;
        /**
          * @default []
         */
        "chatSuggestions": string[];
        /**
          * If true, the chat panel opens automatically when the chatbot mounts. Useful for demos, onboarding flows, or pages where engagement is desired.
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * @default false
         */
        "hideBranding": boolean;
        /**
          * @default {}
         */
        "meta": Object;
        /**
          * Persist the conversation in localStorage so it survives page reloads and navigations. Set to `false` to disable persistence entirely.
          * @default true
         */
        "persistConversation": boolean;
        /**
          * Override the localStorage key used to persist the conversation. Defaults to `cloudtrain-chat:<apiKey-suffix>` for per-agent isolation.
         */
        "persistStorageKey"?: string;
        /**
          * How long (in hours) to keep a persisted conversation before discarding on next load. Defaults to 7 days. Pass `0` to keep indefinitely.
          * @default 24 * 7
         */
        "persistTtlHours": number;
        /**
          * @default 'bottom-right'
         */
        "position": 'bottom-right' | 'bottom-left';
        /**
          * Field configuration for the pre-chat lead-capture form. Each field renders as an input; required fields must be filled to submit.  Example: [{ name: 'email', label: 'Your email', type: 'email', required: true }]
          * @default []
         */
        "preChatFields": PreChatField[];
        /**
          * If true, gate the conversation behind a pre-chat form. Captured values are merged into `meta` so the AI sees the lead's context. Requires `preChatFields` to be non-empty — otherwise this flag is a no-op.
          * @default false
         */
        "requirePreChat": boolean;
        /**
          * Milliseconds between each character reveal in the streaming animation. `0` (default) shows characters as fast as they arrive from the network. A positive value (e.g. `20`) produces a typewriter effect.
          * @default 0
         */
        "revealDelayMs": number;
        /**
          * @default 'system'
         */
        "theme": 'light' | 'dark' | 'system';
        /**
          * @default 'How can I help you today?'
         */
        "welcomeMessage": string;
        "welcomeSubtitle"?: string;
    }
}
export interface CloudtrainChatbotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCloudtrainChatbotElement;
}
declare global {
    interface HTMLCloudtrainChatbotElementEventMap {
        "chatOpened": void;
        "chatClosed": void;
        "messageSent": { text: string };
        "messageReceived": { text: string };
        "conversationReset": void;
        "errorOccurred": { message: string };
        "leadCaptured": CapturedLead;
    }
    interface HTMLCloudtrainChatbotElement extends Components.CloudtrainChatbot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCloudtrainChatbotElementEventMap>(type: K, listener: (this: HTMLCloudtrainChatbotElement, ev: CloudtrainChatbotCustomEvent<HTMLCloudtrainChatbotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCloudtrainChatbotElementEventMap>(type: K, listener: (this: HTMLCloudtrainChatbotElement, ev: CloudtrainChatbotCustomEvent<HTMLCloudtrainChatbotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCloudtrainChatbotElement: {
        prototype: HTMLCloudtrainChatbotElement;
        new (): HTMLCloudtrainChatbotElement;
    };
    interface HTMLElementTagNameMap {
        "cloudtrain-chatbot": HTMLCloudtrainChatbotElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface CloudtrainChatbot {
        "apiKey": string;
        "avatarUrl"?: string;
        /**
          * @default 'https://cloudtrain.ai'
         */
        "baseUrl"?: string;
        "botName"?: string;
        /**
          * @default []
         */
        "chatSuggestions"?: string[];
        /**
          * If true, the chat panel opens automatically when the chatbot mounts. Useful for demos, onboarding flows, or pages where engagement is desired.
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * @default false
         */
        "hideBranding"?: boolean;
        /**
          * @default {}
         */
        "meta"?: Object;
        /**
          * Fired when the chat panel closes.
         */
        "onChatClosed"?: (event: CloudtrainChatbotCustomEvent<void>) => void;
        /**
          * Fired when the chat panel opens.
         */
        "onChatOpened"?: (event: CloudtrainChatbotCustomEvent<void>) => void;
        /**
          * Fired when the user resets the conversation.
         */
        "onConversationReset"?: (event: CloudtrainChatbotCustomEvent<void>) => void;
        /**
          * Fired when an error happens during send/stream. Detail: error message.
         */
        "onErrorOccurred"?: (event: CloudtrainChatbotCustomEvent<{ message: string }>) => void;
        /**
          * Fired when the pre-chat lead form is submitted. Detail: the captured field values.
         */
        "onLeadCaptured"?: (event: CloudtrainChatbotCustomEvent<CapturedLead>) => void;
        /**
          * Fired when a complete AI reply has finished streaming. Detail: the final text.
         */
        "onMessageReceived"?: (event: CloudtrainChatbotCustomEvent<{ text: string }>) => void;
        /**
          * Fired when the user submits a message. Detail: the message text.
         */
        "onMessageSent"?: (event: CloudtrainChatbotCustomEvent<{ text: string }>) => void;
        /**
          * Persist the conversation in localStorage so it survives page reloads and navigations. Set to `false` to disable persistence entirely.
          * @default true
         */
        "persistConversation"?: boolean;
        /**
          * Override the localStorage key used to persist the conversation. Defaults to `cloudtrain-chat:<apiKey-suffix>` for per-agent isolation.
         */
        "persistStorageKey"?: string;
        /**
          * How long (in hours) to keep a persisted conversation before discarding on next load. Defaults to 7 days. Pass `0` to keep indefinitely.
          * @default 24 * 7
         */
        "persistTtlHours"?: number;
        /**
          * @default 'bottom-right'
         */
        "position"?: 'bottom-right' | 'bottom-left';
        /**
          * Field configuration for the pre-chat lead-capture form. Each field renders as an input; required fields must be filled to submit.  Example: [{ name: 'email', label: 'Your email', type: 'email', required: true }]
          * @default []
         */
        "preChatFields"?: PreChatField[];
        /**
          * If true, gate the conversation behind a pre-chat form. Captured values are merged into `meta` so the AI sees the lead's context. Requires `preChatFields` to be non-empty — otherwise this flag is a no-op.
          * @default false
         */
        "requirePreChat"?: boolean;
        /**
          * Milliseconds between each character reveal in the streaming animation. `0` (default) shows characters as fast as they arrive from the network. A positive value (e.g. `20`) produces a typewriter effect.
          * @default 0
         */
        "revealDelayMs"?: number;
        /**
          * @default 'system'
         */
        "theme"?: 'light' | 'dark' | 'system';
        /**
          * @default 'How can I help you today?'
         */
        "welcomeMessage"?: string;
        "welcomeSubtitle"?: string;
    }

    interface CloudtrainChatbotAttributes {
        "apiKey": string;
        "baseUrl": string;
        "theme": 'light' | 'dark' | 'system';
        "hideBranding": boolean;
        "botName": string;
        "avatarUrl": string;
        "welcomeMessage": string;
        "welcomeSubtitle": string;
        "position": 'bottom-right' | 'bottom-left';
        "revealDelayMs": number;
        "defaultOpen": boolean;
        "persistConversation": boolean;
        "persistTtlHours": number;
        "persistStorageKey": string;
        "requirePreChat": boolean;
    }

    interface IntrinsicElements {
        "cloudtrain-chatbot": Omit<CloudtrainChatbot, keyof CloudtrainChatbotAttributes> & { [K in keyof CloudtrainChatbot & keyof CloudtrainChatbotAttributes]?: CloudtrainChatbot[K] } & { [K in keyof CloudtrainChatbot & keyof CloudtrainChatbotAttributes as `attr:${K}`]?: CloudtrainChatbotAttributes[K] } & { [K in keyof CloudtrainChatbot & keyof CloudtrainChatbotAttributes as `prop:${K}`]?: CloudtrainChatbot[K] } & OneOf<"apiKey", CloudtrainChatbot["apiKey"], CloudtrainChatbotAttributes["apiKey"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cloudtrain-chatbot": LocalJSX.IntrinsicElements["cloudtrain-chatbot"] & JSXBase.HTMLAttributes<HTMLCloudtrainChatbotElement>;
        }
    }
}
