/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CloudtrainChatbot {
        "apiKey": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-key"?: string;
        "chatSuggestions": string[];
        "theme": 'light' | 'dark' | 'system';
    }
}
declare global {
    interface HTMLCloudtrainChatbotElement extends Components.CloudtrainChatbot, HTMLStencilElement {
    }
    var HTMLCloudtrainChatbotElement: {
        prototype: HTMLCloudtrainChatbotElement;
        new (): HTMLCloudtrainChatbotElement;
    };
    interface HTMLElementTagNameMap {
        "cloudtrain-chatbot": HTMLCloudtrainChatbotElement;
    }
}
declare namespace LocalJSX {
    interface CloudtrainChatbot {
        "apiKey": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-key"?: string;
        "chatSuggestions"?: string[];
        "theme"?: 'light' | 'dark' | 'system';
    }
    interface IntrinsicElements {
        "cloudtrain-chatbot": CloudtrainChatbot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cloudtrain-chatbot": LocalJSX.CloudtrainChatbot & JSXBase.HTMLAttributes<HTMLCloudtrainChatbotElement>;
        }
    }
}
